# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ta6i1JUDNRXXViHF9mxxaK6OtKRpkF7U
"""

import pandas as pd
import numpy as np
print("1. version of the packeges: ")
print(pd.__version__)
np.__version__

index1 = [10, 20, 30, 40, 50, 60, 70]
list = ['Science', 'Maths', 'physics', 'hindi',
            'Tamil', 'foreign', 'German']
print("2. panda series")
x = pd.Series(list, index = index1)
print(x)

data = [1,2,3,4,5,6, 7,8,9]
ser = pd.Series(data)
print("3. panda series with odd index")
print(ser[0:10:2])

dates = pd.date_range(start = '05-01-2021', end = '05-12-2021')
print("4. Series of dates")
print(dates)

import pandas as pd
dictionary = {'name': ['Vinay', 'Kushal', 'Aman'],
              'age' : [22, 25, 24],
              'occ' : ['engineer', 'doctor', 'accountant']}

dataframe = pd.DataFrame(dictionary)
print("5. corresponding dataframe for given dictionary:")
print(dataframe)

lists = [[2, 'Vishal', 22],
         [1, 'Kushal', 25],
         [1, 'Aman', 24]]

dataframe = pd.DataFrame(lists, columns = ['id', 'name', 'age'])
print("6. corresponding  dataframe for given 2D list: ")

print(dataframe)

df1=dataframe.rename({0: 'r1', 1: 'r2',2:'r3'})
print("7. Renaming the row Index for above dataframe")
print(df1)

df1.columns=['C1','C2','C3']
print("Renaming column indexes:")
print(df1)

dataframe = pd.read_csv('Customer.csv')
print("8.Importing dataset,Reading the csv file and store it in a dataframe: ")
print(dataframe)

A = pd.DataFrame(dataframe)
print("9. Setting the row index for the dataframe:")
print(A)

A_customindex = A.set_index('Customer ID') # custom indexed dataframe with column, 'id'
print("Setting column indexfor the dataframe:")
print(A_customindex)

print("10.Displaying first 5 rows:")
A_customindex.head(5)

print("Displaying last 5 rows and not the outpu:")
A_customindex.tail(5)

print("11. Displaying the datatype of all the attributes:")
type('A_customindex')

print("12.Displaying the size of dataframe:")
A_customindex.size

print("12.Displaying the shape of dataframe: ")
A_customindex.shape

print("Displaying the information of dataframe: ")
A_customindex.ndim

print("13.Describing the dataset of dataframe: ")
A_customindex.describe()

print("14. Displaying the statistical information about the dataframe:")
A_customindex.mean()

print("15. Count of number of unique  values in each attribute")
A_customindex.value_counts()

A_customindex.nunique()

b=A_customindex.isnull()
print("16. NULL values in dataframe:")
print(b)

print("17. Accessing alternative rows in the dataframe using iloc:")
A_customindex.iloc[:2]